spring.application.name=api

spring.datasource.url=<jdbc-connection-string>
spring.datasource.driverClassName=<driver-class>
spring.datasource.username=<db-username>
spring.datasource.password=<db-password>

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.defer-datasource-initialization=true

security.jwt.secret-key=<base64-encoded-secret-key>
security.jwt.expiration-time-ms=<jwt-expiry-in-milliseconds>
security.refresh-token.expiration-days=<refresh-token-expiry-in-days>
